### ISSUE TITLE
1.6.0+git1 doesn't work with included mapbox-gl-native

### ISSUE THREAD

**Issue by PureTryOut** [rinigus/pkg-mapbox-gl-native#3]
It tries to use `platform/default/thread.cpp` [here](https://github.com/rinigus/pkg-mapbox-gl-native/blob/sfos/mapbox-gl-native-lib.pro#L35), but that file doesn't exist anymore upstream or in your fork. https://github.com/rinigus/mapbox-gl-native/tree/f84d4ad4f6def4e5d80e93e679f47c815028f2ca/platform/default

**Comment by rinigus** [comment]
We don't use .pro for building, see rpm SPEC file for use with cmake.

Turned out that I deleted .pro in my local repo and forgot to push it to github. Sorry.
